image:
  repository: my-docker-image
  tag: my-image-tag
  args: ["command-arg"]

nameOverride: "notebook"
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::account-id:role/env-service-notebook"

ingress:
  enabled: true
  className: nginx

environment: "prod"
env:
  CONFIG: >-
    {
      "json_field": [
        "array_value"
      ]
    }

sidecars:

  my-sidecar:
    image:
      repository: my-docker-image
      tag: my-image-tag
      pullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["echo", "hello world"]
    env:
      MY_ENV: my-env-value
