image:
  repository: my-docker-image
  tag: my-image-tag
  args: ["command-arg"]

nameOverride: "notebook"
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::account-id:role/env-service-notebook"

environment: "prod"
env:
  CONFIG: >-
    {
      "json_field": [
        "array_value"
      ]
    }
