image:
  repository: my-docker-image
  tag: my-image-tag
  args: ["command-arg"]

nameOverride: "notebook"
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::account-id:role/env-service-notebook"

ingress:
  enabled: true
  className: nginx

environment: "prod"
env:
  CONFIG: >-
    {
      "json_field": [
        "array_value"
      ]
    }

sidecars:

  my-sidecar:
    image:
      repository: my-docker-image
      tag: my-image-tag
      pullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["echo", "hello world"]
    env:
      - key: MY_ENV_VAR
        value: my-env-value
    ports:
      - containerPort: 8080
        protocol: TCP
      - name: http
    resources:
      limits:
        cpu: 10m
        memory: 32Mi
      requests:
        cpu: 10m
    readinessProbe:
      httpGet:
        path: /health
        port: 5000
      initialDelaySeconds: 5
    livenessProbe:
      httpGet:
        path: /health
        port: 5000
      initialDelaySeconds: 5
      periodSeconds: 30
