apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "service.prefixedName" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "service.prefixedName" . }}