apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: service-{{ .Chart.Name }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}