apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.prefixedName" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}